#!/usr/bin/env bash
# deploy_testnet.sh — deploy the PERSISTENT base infrastructure to Stellar
# testnet and record the addresses. Unlike e2e_testnet.sh (ephemeral smoke),
# this produces long-lived contract ids for the backend to integrate against.
#
# What it deploys (dependency order): the two stateless verifiers, the wallet
# factory (+ uploaded wallet wasm hash), the three admin singletons
# (kyc-allowlist, emergency-freeze, registry-anchor), the fraction-token factory
# (+ uploaded token wasm hash), and the marketplace settler. Per-artwork
# FractionTokens and per-offering OfferingEscrows are deployed on demand by the
# backend and are NOT part of this base deploy.
#
# Admin for every admin-gated contract = the deploying identity (single key on
# testnet; rotate to a multi-sig account with each contract's set_admin later).
# No secrets: a fresh friendbot-funded identity is generated per run.
#
# Usage:  bash scripts/deploy_testnet.sh
# Output: prints a summary block AND writes deployments/testnet-latest.env

set -euo pipefail

STELLAR_RPC_URL="${STELLAR_RPC_URL:-https://soroban-testnet.stellar.org}"
STELLAR_NETWORK_PASSPHRASE="${STELLAR_NETWORK_PASSPHRASE:-Test SDF Network ; September 2015}"
NET=(--rpc-url "$STELLAR_RPC_URL" --network-passphrase "$STELLAR_NETWORK_PASSPHRASE")

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

wasm_path() { echo "target/wasm32v1-none/release/${1//-/_}.wasm"; }
step() { echo; echo "==> $*" >&2; }

# --- identity -----------------------------------------------------------------
IDENTITY="tove-deploy-${RANDOM}${RANDOM}"
step "generate + friendbot-fund identity '$IDENTITY'"
stellar keys generate "$IDENTITY" "${NET[@]}" --fund >&2
ADMIN="$(stellar keys address "$IDENTITY")"
echo "    admin (deployer) = $ADMIN" >&2

deploy() { # deploy <crate> [-- constructor args...]
  local crate="$1"; shift
  stellar contract deploy --wasm "$(wasm_path "$crate")" --source "$IDENTITY" "${NET[@]}" "$@"
}
upload() { # upload <crate> -> wasm hash
  stellar contract upload --wasm "$(wasm_path "$1")" --source "$IDENTITY" "${NET[@]}"
}

step "build (ensure wasms are fresh)"
stellar contract build >&2

# --- 1. stateless verifiers ---------------------------------------------------
step "deploy tove-webauthn-verifier"
WEBAUTHN_VERIFIER="$(deploy tove-webauthn-verifier)"
step "deploy tove-ed25519-verifier"
ED25519_VERIFIER="$(deploy tove-ed25519-verifier)"

# --- 2. wallet stack ----------------------------------------------------------
step "upload tove-smart-wallet wasm (canonical hash)"
WALLET_WASM_HASH="$(upload tove-smart-wallet)"
step "deploy tove-wallet-factory (admin + canonical wallet hash)"
WALLET_FACTORY="$(deploy tove-wallet-factory -- --admin "$ADMIN" --wasm_hash "$WALLET_WASM_HASH")"

# --- 3. compliance + provenance singletons ------------------------------------
step "deploy tove-kyc-allowlist"
KYC_ALLOWLIST="$(deploy tove-kyc-allowlist -- --admin "$ADMIN")"
step "deploy tove-emergency-freeze"
EMERGENCY_FREEZE="$(deploy tove-emergency-freeze -- --admin "$ADMIN")"
step "deploy tove-registry-anchor"
REGISTRY_ANCHOR="$(deploy tove-registry-anchor -- --admin "$ADMIN")"

# --- 4. fraction token factory ------------------------------------------------
step "upload tove-fraction-token wasm (canonical hash)"
TOKEN_WASM_HASH="$(upload tove-fraction-token)"
step "deploy tove-fraction-factory (admin + canonical token hash)"
FRACTION_FACTORY="$(deploy tove-fraction-factory -- --admin "$ADMIN" --wasm_hash "$TOKEN_WASM_HASH")"

# --- 5. marketplace settler (needs the factory address) -----------------------
step "deploy tove-marketplace-settler (admin + factory)"
MARKETPLACE_SETTLER="$(deploy tove-marketplace-settler -- --admin "$ADMIN" --factory "$FRACTION_FACTORY")"

# --- record -------------------------------------------------------------------
mkdir -p deployments
OUT="deployments/testnet-latest.env"
{
  echo "# Tove Heritage — testnet base-infrastructure deployment"
  echo "# Generated by scripts/deploy_testnet.sh. Testnet resets quarterly."
  echo "STELLAR_NETWORK=testnet"
  echo "STELLAR_RPC_URL=$STELLAR_RPC_URL"
  echo "STELLAR_NETWORK_PASSPHRASE=$STELLAR_NETWORK_PASSPHRASE"
  echo "ADMIN=$ADMIN"
  echo "WEBAUTHN_VERIFIER=$WEBAUTHN_VERIFIER"
  echo "ED25519_VERIFIER=$ED25519_VERIFIER"
  echo "WALLET_WASM_HASH=$WALLET_WASM_HASH"
  echo "WALLET_FACTORY=$WALLET_FACTORY"
  echo "KYC_ALLOWLIST=$KYC_ALLOWLIST"
  echo "EMERGENCY_FREEZE=$EMERGENCY_FREEZE"
  echo "REGISTRY_ANCHOR=$REGISTRY_ANCHOR"
  echo "TOKEN_WASM_HASH=$TOKEN_WASM_HASH"
  echo "FRACTION_FACTORY=$FRACTION_FACTORY"
  echo "MARKETPLACE_SETTLER=$MARKETPLACE_SETTLER"
} | tee "$OUT"

echo >&2
echo "==> wrote $OUT" >&2
echo "==> DEPLOY OK" >&2
